# Generated by Django 3.2.5 on 2021-08-06 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega24', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='valid_until',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Coupon is valid until'),
        ),
    ]
