# Generated by Django 3.2.5 on 2021-08-06 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mega24', '0002_discount_valid_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponoperation',
            name='valid_from',
        ),
        migrations.AddField(
            model_name='couponoperation',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='couponoperation',
            name='valid_to',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
