# Generated by Django 3.2.5 on 2021-08-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega24', '0003_auto_20210806_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponoperation',
            name='valid_to',
            field=models.DateTimeField(),
        ),
    ]
