# Generated by Django 3.2.5 on 2021-08-06 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mega24', '0004_alter_couponoperation_valid_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponoperation',
            name='company',
        ),
        migrations.AddField(
            model_name='couponoperation',
            name='discount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='mega24.discount'),
            preserve_default=False,
        ),
    ]
