# Generated by Django 3.2.5 on 2021-08-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega24', '0005_auto_20210806_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponoperation',
            name='status',
            field=models.IntegerField(choices=[(0, 'not active'), (1, 'activated'), (2, 'expired')], default=0),
        ),
    ]
