# Generated by Django 3.2.5 on 2021-08-09 05:34

from django.db import migrations, models
import mega24.models


class Migration(migrations.Migration):

    dependencies = [
        ('mega24', '0006_alter_couponoperation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pin',
            field=models.CharField(default=mega24.models.get_random_pin, max_length=4, verbose_name='Пин-код'),
        ),
    ]
